# Release: https://github.com/scrtlabs/secret-ai-caddy/releases/tag/v0.1.17
# Workflow URL: https://github.com/scrtlabs/secret-ai-caddy/actions/runs/26455659769
# Commit: https://github.com/scrtlabs/secret-ai-caddy/commit/63080fd8a9b9c59730a226716f4e7e215369e07a
# Dockerfile Path: Dockerfile
# Docker Compose Location: ./docker-compose-secretvm.yaml
version: '3'
services:
  app:
    image: ghcr.io/scrtlabs/secret-ai-caddy@sha256:52f084d1ff7ef9e73f56ed1b7e5369aa8ea181ad047b9ed4b329e562dcb36c0e
    ports:
      - '8080:80'
