# Release: https://github.com/scrtlabs/secret-ai-caddy/releases/tag/v0.1.12
# Workflow URL: https://github.com/scrtlabs/secret-ai-caddy/actions/runs/23814220239
# Commit: https://github.com/scrtlabs/secret-ai-caddy/commit/eaef526982e0fe09c89c11fc74eda741fb083154
# Dockerfile Path: Dockerfile
# Docker Compose Location: ./docker-compose-secretvm.yaml
version: '3'
services:
  app:
    image: ghcr.io/scrtlabs/secret-ai-caddy@sha256:5bbfd6a202ad7f347f42867ae00aab867d76bc50c7e5cb1d12c524b05bedfc03
    ports:
      - '80'
      - '443'
      - '21434'
      - '22434'
      - '23434'
