# Release: https://github.com/scrtlabs/secret-ai-caddy/releases/tag/v0.1.5
# Workflow URL: https://github.com/scrtlabs/secret-ai-caddy/actions/runs/17125060155
# Commit: https://github.com/scrtlabs/secret-ai-caddy/commit/5a7cc71443b26ab98b51e72b99227c6b76f93068
# Dockerfile Path: Dockerfile
# Docker Compose Location: ./docker-compose-secretvm.yaml
version: '3'
services:
  app:
    image: ghcr.io/scrtlabs/secret-ai-caddy@sha256:cf1f011cc8f191d18f0e5cc850c199f43a2873420bee83324794ec43962c7546
    ports:
      - '3000:80'
